# This is a basic workflow to help you get started with Actions

name: HBaserepo-Hello-world-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" , "development" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  Pr_Test:
    runs-on: ubuntu-latest
    steps:
      - name: check if githubcli is present or not
        run: |
           gh --version
      - name: Create Pull Request
        run: |
           echo "creating a pr from development to new_pr_test"
           curl -X POST \
             -H "Authorization: Bearer ${{ secrets.SUDHANSU_PAT_FG }}" \
             -H "Accept: application/vnd.github+json" \ https://api.github.com/repos/${{ github.repository }}/pulls \
           -d '{
             "title": "Auto PR",
             "head": "development",
             "base": "new_pr_test",
             "body": "This PR was created by GitHub Actions"
           }'
      
